services:
  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
  elasticsearch:
    image: elasticsearch:8.9.2
    container_name: elasticsearch
    ports:
      - 9200:9200
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
  kafka:
    image: bitnami/kafka
    container_name: kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    ports:
      - 9092:9092